# Data Management

## Write a Living Data Management Plan (DMP) {#living-dmp}

***Description:*** *Many researchers are aware of the two-page data management plan (DMP) for a grant application, but you may not be aware of the more useful type of DMP: a living DMP. This document describes how data will be actively managed during a project and may be updated whenever necessary to reflect current data practices. A living DMP is a useful touchstone for understanding where data lives, how it’s labelled, how it moves through the research process, and who will oversee the data management. This exercise guides you through the process of creating a living DMP for your research.*

***Instructions:*** *Pick a project and answer the following questions to build your living DMP. This DMP may be changed at any time to improve practices. If you are doing collaborative research, work through this exercise with your collaborators to agree on shared conventions.*

---

**Write a short summary of what project this DMP is for:**

&nbsp;

&nbsp;

&nbsp;

**How will your data be organized? (See [Exercise 3.1: Set Up a File Organization System](#file-organization).)**

&nbsp;

&nbsp;

&nbsp;

**What naming convention(s) will you use for your data? (See [Exercise 3.2: Create a File Naming Convention](#file-naming).)**

&nbsp;

&nbsp;

&nbsp;

**Where will data be stored? How will data be backed up? (See [Exercise 4.1: Store and Back Up the Data](#storage).)**

&nbsp;

&nbsp;

&nbsp;

**How will you document your research? Where will your research notes be stored?**

&nbsp;

&nbsp;

&nbsp;

**How will data move through the collection and analysis pipelines?**

&nbsp;

&nbsp;

&nbsp;

**Do you need to do any version control on your files? How will that be done?**

&nbsp;

&nbsp;

&nbsp;

**As necessary, record any project roles and responsibilities around data management:**

&nbsp;

&nbsp;

&nbsp;



## Determine Data Stewardship {#data-governance}

***Description:*** *It is often helpful to be up front about requirements and permissions around research data. This exercise encourages you to discuss these issues with supervisors and peers to make sure that there are no misunderstandings about who has what rights to use, retain, and share data.*

***Instructions:*** *Determine which research data should be discussed. Bring together the Principle Investigator, the researcher collecting the data, and anyone else who works with that data. As a group, answer the questions in the exercise, making sure that everyone agrees on the final decisions. Record the results of the discussion and save them with the project files.*

***Source:*** *This exercise was adapted from the "Project Close Out Checklist" [@briney_project_2020].*

---

**What data is being discussed?**

&nbsp;

&nbsp;

&nbsp;

**Are there security or intellectual property restrictions on the data and, if so, what are they?**

&nbsp;

&nbsp;

&nbsp;

**Are there any requirements to publicly share the data and, if so, what are they?**

&nbsp;

&nbsp;

&nbsp;

**Who will store the copy of record of the data and for how long?**

&nbsp;

&nbsp;

&nbsp;

**Who is allowed to keep a copy of the data after the project ends? Which data?**

&nbsp;

&nbsp;

&nbsp;

**Who is allowed to reuse the data after the project ends? Are there any requirements for reuse, such as co-authorship?**

&nbsp;

&nbsp;

&nbsp;

**Who keeps any physical research notebooks after the project ends?**

&nbsp;

&nbsp;

&nbsp;
