# Project Wrap Up

The end of a project is a key time to perform data management activities in order to set yourself up for future data reuse. This is because you still remember all of the important details about your data and can make good decisions about preparing it for the future. This chapter has three exercises to work through for project wrap up: a worksheet on converting data to more open file types; a checklist for populating a project Archive folder; and a checklist for preparing data for reuse, which leverages the previous two exercises.

This chapter also covers project wrap up in the form of separating from your institution. This checklist exercise for the departing researcher is important to work through so that critical data does not get lost in the transition. A fuller version of this checklist, intended for both the departing personnel and a project administrator to work through together, is also available [@goben_data_2023].

## Prepare Data for Future Use {#future-use}

***Description:*** *The end of a project is a good time to prepare data for potential future reuse, as you still know the important details about the data to record and have access to any software used to create the data. This checklist exercise walks you through steps to gather your data into a central place and document the project. Working through the checklist results in project data being in one central location, well documented, and organized and formatted in a way to make future reuse easier.*

***Instructions:*** *Gather all of the data from a project and work through the checklist to organize and document the data for future reuse. This exercise refers to several other exercises in the Workbook that should be completed during this process, if they have not been already*

***Source:*** *This exercise was adapted from the "Project Close Out Checklist" [@briney_project_2020].*

---

**Prepare Data**

\_\_ Move all data into one central project folder; this folder may have sub-folders and should be organized however makes sense for your data.

\_\_ As necessary, work through [Exercise 7.2: Convert Data File Types](#file-type) to copy data into more open/common file formats.

**Back Up Your Research Notes**

\_\_ If your notes are electronic, save a copy in the project folder

\_\_ If your notes are physical, scan them and save a copy in the project folder.

**Create a Project Archive Folder**

\_\_ Work through [Exercise 7.3: Create an Archive Folder](#archive-folder).

\_\_ Put the Archive folder in the project folder.

**Create a Project-Level README File**

\_\_ If you haven't done so already, work through [Exercise 2.2: Project-Level README.txt](#readme-txt).

\_\_ Store a copy of the README file with the data.

**Save Files in a Stable Location**

\_\_ Save the project folder on a storage system that you will have access to for the next several years.



## Convert Data File Types {#file-type}

***Description:*** *Data is often stored in a file type that can only be opened by specific, costly software – this is referred to as a “proprietary file type.” You can tell that you have data in a proprietary file type if you lose access to the data when you lose access to the software. When data is in a proprietary file type, it’s always a good idea to copy the data into a more common, open file type as a backup; you may lose a bit of functionality, but it’s better to have a backup than to not have your data at all! This exercise works through identifying possible alternative file types for the data's proprietary file type before instructing you to make a copy of the data in the new file type.*

***Instructions:*** *For any data in a proprietary file type, identify the data and answer the following questions. Once you have picked a more open, common file type, make a copy of the data in that file type but do not delete the original data. (Keeping a copy in the original file format means that, while you access to the necessary software, your data has full functionality. If you lose access to the software, you'll still have your data in some format, which is better than not having your data at all.)*

---

**Is your data stored in a proprietary file type? What file type and how does this limit future data reuse?**

*Example: Data is stored in a .CZI file format, which is a proprietary Zeiss microscope image format. These files do not open in other software.*

&nbsp;

&nbsp;

&nbsp;

**Is it possible to convert your data to other file types? If so, list the possible types:**

*Example: I can use the Bio-Formats tool to convert .CZI files to: .AVI, .CH5, .DCM/.DICOM, .EPS/.EPSI/.PS, .ICS/.IDS, .JPG, .JP2/.J2K/.JPF, .MOV, .OME.TIFF/.OME.TIF, .OME/.OME.XML, .PNG, or .TIFF/.TIF.*

&nbsp;

&nbsp;

&nbsp;

**Which of the possible file types are in common use? Which of the possible file types can be opened by multiple software programs?**

*Example: JPG, PNG, and TIFF are all image formats in common use. OME-TIFF is a common image format within microscopy; most software will read the TIFF portion of the file but only some software will read the extra OME metadata. Common movie file types are AVI and MOV.*

&nbsp;

&nbsp;

&nbsp;

**Of the possible options above, do you have a preference for a specific file type?**

*Example: I prefer an image file over a movie file. TIFF is best because it doesn't lose resolution due to compression and can store all of the 4-dimensional image layers. OME-TIFF gives all of the benefits of TIFF but with added metadata.*

&nbsp;

&nbsp;

&nbsp;

**Pick one of the more open or common file types and copy your important data files into that file type. Do not delete the original files.**

*Example: I will convert my data to OME-TIFF files.*

&nbsp;

&nbsp;

&nbsp;



## Create an Archive Folder {#archive-folder}

***Description:*** *To save your future-self time spent digging through all of your research files, set aside the most important files into a separate “Archive” folder. Do this at the end of the project while you still remember which files are important and where they are located. The Archive folder should only contain a small subset of the most important documents that are likely to be reused; you may still need to go through all of your files but, in the majority of instances, you will save time by easily finding what you need in the Archive folder.*

***Instructions:*** *This exercise consists of a checklist of the key documents that are likely to be most useful in a research project archive. Create a separate folder within the larger project folder (or in a highly visible place within the storage system) labelled “Archive”. Copy – do not move – the files on this checklist into the Archive folder. Add copies other important research documents, as needed. Remember, the Archive folder does not need to be comprehensive, so focus on the subset of files that are most likely to be reused or referenced in the future.*

***Source:*** *This exercise was adapted from the "Project Close Out Checklist" [@briney_project_2020].*

---

**Project Documentation**

\_\_ README file of project information

**Data Snapshots**

\_\_ Important raw data

\_\_ Key data analyses

\_\_ Final published data

**Code**

\_\_ Analysis code

\_\_ Record software version, as appropriate

**Other Research Documents**

\_\_ Protocols

\_\_ Survey instruments

**Research Notes**

\_\_ Scans of research notebook

\_\_ Digital notes

**Images**

\_\_ Flat files of figures (e.g. .JPG or .TIFF)

\_\_ Editable image files (e.g. .XLSX or .PSD)

**Publications**

\_\_ Published articles in .PDF format

\_\_ Accepted version of articles in editable document format (e.g. .DOCX)

\_\_ Poster files

**Administrative Documents**

\_\_ Grant proposals

\_\_ Grant progress reports and final report



## Separate from the Institution {#separation}

***Description:*** *Researchers regularly leave institutions in order to take new jobs. For how common this occurrence is, it represents a critical transition during which data may be lost. This checklist enumerates a number of important steps that researchers can take to ensure that they retain the appropriate data yet leave behind what belongs to the institution.*

***Instructions:*** *The researcher leaving the institution should work through this checklist to ensure they keep the proper information while returning what does not belong to them. The researcher and project administrator may also jointly work through the extended version of this exercise, the Data Departure Checklist [@goben_data_2023].*

***Source:*** *This exercise was adapted from the "Data Departure Checklist" [@goben_data_2023].*

---

**Retain Copies of Data that You Have Permission to Keep**

\_\_ If you have not done so already, work through [Exercise 5.2: Determine Data Stewardship](#data-governance) to determine what data you may retain

\_\_ Identify and keep pertinent research data from personal devices

\_\_ Identify and keep pertinent research data from storage systems (e.g. AWS/Azure, Box, campus HPC, Dropbox, Electronic Lab Notebook, Globus, Google Drive, lab/department/college servers, Microsoft OneDrive, Microsoft Sharepoint, or shared collaborator drives)

\_\_ When appropriate, make a copy of research notes

**Delete Personal Information and Remove Personal Devices**

\_\_ Remove personal information from lab devices

\_\_ Remove personal devices from lab

\_\_ Remove personal access to shared accounts (e.g. lab Github, lab repository page, lab website, mailing lists, or social media)

**Return Lab Hardware**

\_\_ Individual computer / workstation

\_\_ Tablet(s)

\_\_ Peripherals (e.g. keyboard, mouse, monitor)

\_\_ External drives

\_\_ Other lab equipment (e.g. cameras, recording devices)

**Update Research Administration Documents, As Necessary**

\_\_ Update/transfer Institutional Review Board

\_\_ Update/transfer IACUC

\_\_ Update/transfer Data Use Agreements (DUA)

\_\_ Update/transfer Material Transfer Agreements (MTA)

\_\_ Update/transfer research grants

**Handle Email**

\_\_ Set out of office, providing forwarding information

\_\_ Forward/backup important emails

\_\_ Check with University Archivist or Records Manager for retention policies (depends on rank)
